kind: pipeline
name: default

workspace:
  base: /tmp
  path: "."

steps:
- name: Deploy-helm-charts
  image: mellena1/drone-helm-gh-pages-deploy:0.1.1
  pull: always
  settings:
    ssh_key:
      from_secret: key
