kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote
  - ls charts

- name: Deploy-helm-charts
  image: mellena1/drone-helm-gh-pages-deploy:0.1.1
  settings:
    ssh_key:
      from_secret: key
