apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makemkv.fullname" . }}
  labels:
    {{- include "makemkv.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "makemkv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "makemkv.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5800
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: config
            mountPath: /config
          {{- if .Values.persistence.config.subPath }}
            subPath: {{ .Values.persistence.config.subPath }}
          {{ end }}
          - name: output
            mountPath: /output
          {{- if .Values.persistence.output.subPath }}
            subPath: {{ .Values.persistence.output.subPath }}
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
          {{- if .Values.persistence.config.claimName }}
            claimName: "{{ .Values.persistence.config.claimName }}"
          {{- else }}
            claimName: "{{ template "makemkv.fullname" . }}-config"
          {{- end }}
        - name: output
          persistentVolumeClaim:
          {{- if .Values.persistence.output.claimName }}
            claimName: "{{ .Values.persistence.output.claimName }}"
          {{- else }}
            claimName: "{{ template "makemkv.fullname" . }}-output"
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
